### ISSUE TITLE
[EPIC] : Analysis of Sheffield Thyroid cancer

### ISSUE THREAD

**Issue by ns-rse** [ns-rse/sheffield-multicenter-thyroid#1]
The [thyroid-cancer-prediction:ns-rse/evaluate-modelling](https://github.com/ns-rse/thyroid-cancer-prediction/tree/ns-rse/evaluate-modelling) repository/branch has examples of how to use the [TidyModels](https://www.tidymodels.org/) framework to setup data into training and testing datasets and undertake "machine learning" using a range of models. The example is written in [Quarto](https://quarto.org) and rendered to a HTML web-page that is hosted on GitHub and can be viewed [here](https://blog.nshephard.dev/thyroid-cancer-prediction/modelling.html).

Models used...

+ LASSO regression
+ ElasticNet
+ Random Forest
+ Gradient Boosting
+ Support Vector Machines (SVM)

Further these are then summarised using a range of [classification metrics](https://blog.nshephard.dev/thyroid-cancer-prediction/modelling.html#model-assessment) including plotting Receiver Operating Characteristics and the Area Under the Curve.

Now that work is progressing and @mdp21oe has collected ~1500 cases from historical cases of Thyroid cancer at Sheffield Teaching Hospitals we can progress with adapting this workflow to analysing the data set.

## Tasks

+ [x] Copy `r/shf_thy_nod.R` from [thyroid-cancer-prediction : `mdp21oe/sheffield_clean`](https://github.com/ns-rse/thyroid-cancer-prediction/blob/mdp21oe/sheffield_clean/r/shf_thy_nod.R) banch. This will serve as the basis for cleaning the dataset and from now on addition and development should be made to this.
+ [ ] Complete cleaning of data, to include labelling of variables, conversion of dates/times if any to internal elapsed time variables, encoding of categorical variables.
+ [ ] Adapt the code in [thyroid-cancer-prediction : `ns-rse/evaluate-modelling:docs/modelling*.qmd`](https://github.com/ns-rse/thyroid-cancer-prediction/tree/ns-rse/evaluate-modelling/docs) to work with Sheffield data.
+ [ ] Develop assessment of what variables are important using the [LIME](https://cran.r-project.org/web//packages//lime/vignettes/Understanding_lime.html) and [Shapely](https://cran.r-project.org/web/packages/shapr/vignettes/understanding_shapr.html) frameworks.
